# Generated by Django 3.2.21 on 2023-11-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20231126_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='item_type',
            field=models.CharField(choices=[('post', 'post'), ('comment', 'comment')], max_length=10),
        ),
    ]
