# Generated by Django 3.2.21 on 2023-11-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
    ]
